EXTRN INPUTCOM: NEAR   
EXTRN INPUT: NEAR			
EXTRN OUTPUT_UNSIGN_DEC: NEAR		
EXTRN OUTPUT_SIGN_HEX: NEAR		
EXTRN NEWSTR: NEAR

STKS SEGMENT PARA STACK 'STACK'
    DB 200 DUP (0)
STKS ENDS

; Сегмент данных
DATAS SEGMENT PARA PUBLIC'DATA'	
    MENUMSG DB 13
		DB 10
		DB '1 - Input signed binary number', 13, 10
		DB '2 - Output unsigned decimal', 13, 10				
		DB '3 - Output signed hexadecimal', 13, 10				
		DB '0 - Exit', 13, 10, 10		
		DB 'INPUT COMMAND: $'
	ACT DW EXIT, INPUT, OUTPUT_UNSIGN_DEC, OUTPUT_SIGN_HEX
DATAS ENDS	

; Сегмент кода
CODES SEGMENT PARA PUBLIC 'CODE'	
    ASSUME CS:CODES, DS:DATAS, SS:STKS

EXIT PROC NEAR
	MOV AH,4Ch						
	INT 21h
EXIT ENDP

OUTPUTMENU PROC NEAR
	MOV DX, OFFSET MENUMSG
	MOV AH, 9
	INT 21h
	RET
OUTPUTMENU ENDP

MAIN:
	MOV AX, DATAS			
    MOV DS, AX				
		
	MENULOOP:
		CALL OUTPUTMENU		
		CALL INPUTCOM		
		CALL NEWSTR			
		CALL ACT[SI]		
		JMP MENULOOP		
CODES ENDS
END MAIN
